// Cart reducer
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_CART = 'INCREMENT_CART';
export const DECREMENT_CART = 'DECREMENT_CART';
// Product reducer
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCTS_TO_RENDER = 'PRODUCTS_TO_RENDER';
export const FETCH_STORE_INFORMATION = 'FETCH_STORE_INFORMATION';
// User reducer
export const LOGIN = 'LOGIN';
export const CHANGE_LOGGED_IN = 'CHANGE_LOGGED_IN';
export const LOGOUT = 'LOGOUT';